services:
  db:
    image: postgres:16
    container_name: crm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: ./api
    container_name: crm-api
    environment:
      DB_URI: postgres://postgres:123@db:5432/postgres-db
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./web
    container_name: crm-web
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  dbdata: {}

networks:
  app-network:
    driver: bridge
